apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: tanzu-data-services
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: k8s.io/tanzu-data-services
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true