spring.application.name=jms.producer
spring.rabbitmq.addresses=amqp://localhost:5672
spring.rabbitmq.username=${TANZU_RABBITMQ_USER}
spring.rabbitmq.password=${TANZU_RABBITMQ_PASSWORD}
server.port=8077
app.delivery.delay.ms=0
app.queue.name=accounts