spring.application.name=rabbitmq.jms.showcase
app.broker.url=amqp://localhost:5672
spring.rabbitmq.username=${TANZU_RABBITMQ_USER}
spring.rabbitmq.password=${TANZU_RABBITMQ_PASSWORD}
server.port=8855

app.queue.name=accounts
app.message.selector=status = 'ACTIVE' AND (state = 'NY' OR state = 'CA') AND city IN ('NY', 'LA', 'IM','ANI') AND zip LIKE '90%'